apiVersion: apps/v1
kind: Deployment
metadata:
  name: complete-production-e2e-pipeline-deployment
  labels:
    app: complete-production-e2e-pipeline
spec:
  replicas: 1
  selector:
    matchLabels:
      app: complete-production-e2e-pipeline
  template:
    metadata:
      labels:
        app: complete-production-e2e-pipeline
    spec:
      containers:
      - name: complete-production-e2e-pipeline
        image: kummer/complete-prodcution-e2e-pipeline:1.0.0-39
        ports:
        - containerPort: 8080